### ISSUE TITLE
recaptcha__en.js:411 Uncaught Error: reCAPTCHA has already been rendered in this element

### ISSUE THREAD

**Issue by finkbg** [escaladesports/gatsby-plugin-recaptcha#1]
Using the plugin with 'react-recaptcha' in invisible mode.

This only happens in production build, not in develop.

One question - why does the plugin load 2 scripts - recaptcha_en.js and recaptcha/api.js?

**Comment by kennedyrose** [comment]
That would likely be something in react-recaptcha. This plugin only loads `https://www.google.com/recaptcha/api.js` in your page. It doesn't load anything else.
